#!/bin/sh

SELFDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
WP=/data/wallpapers/W_2014_361_DARKWING.jpg

bspc config top_padding 20
bspc config border_width 5
bspc config window_gap 15

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_by_distance true

bspc monitor -d I II III IV V VI VII VIII IX X

# Skype
bspc rule -a Skype desktop="^8" follow=off
bspc rule -a froyomuffin - Skype™ desktop="^8" follow=off

# Linphone
bspc rule -a Linphone desktop="^8" follow=off

# Steam
bspc rule -a Steam desktop='^10' follow=off
bspc rule -a Friends desktop='^10' follow=off

# Spotify
bspc rule -a Spotify desktop='^9'

exec /usr/bin/compton --config ~/.config/compton/config &
exec $SELFDIR/min-bar &
exec feh --bg-fill $WP
