#!/bin/sh

SELFDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
WP=/data/wallpapers/W_2014_361_DARKWING.jpg

bspc config top_padding 20
bspc config border_width 5
bspc config window_gap 15

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_by_distance true

bspc monitor -d I II III IV V VI VII VIII IX X

#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
#bspc rule -a Gimp desktop=^8 follow=on floating=on
#bspc rule -a Chromium desktop=^2
#bspc rule -a mplayer2 floating=on
bspc rule -a Skype floating=on

exec /usr/bin/compton --config ~/.config/compton/config &
exec $SELFDIR/min-panel &
exec feh --bg-fill $WP
